In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

In [2]:
df = pd.read_csv('DataFrame#2.csv',index_col=0)
df2 = df.copy()

In [3]:
le = preprocessing.LabelEncoder()
lable = le.fit_transform(df2['developer'])
print(le.classes_)
print (lable)
df2 = df2.drop("developer", axis = 'columns')
df2 ['developer'] = lable
df2

['10tacle Studios' '10tacle Studios, Fusionsphere Systems'
 '11 bit studios' ... 'tobyfox' 'tobyfox, 8-4' 'zSlide']
[1350 1350 1115 ...   58  116 1625]


name  hit    Year      price  \
0                     Grand Theft Auto IV    1  2008.0  24.380000   
1                     Grand Theft Auto IV    1  2008.0  24.380000   
2                      Super Mario Galaxy    1  2007.0  69.990000   
3                    Super Mario Galaxy 2    1  2010.0  30.360000   
4                   Red Dead Redemption 2    1  2018.0  17.950000   
...                                   ...  ...     ...        ...   
7667                       Fighter Within    0  2013.0  11.680000   
7668                        Homie Rollerz    0  2008.0  31.958605   
7669             Fast & Furious: Showdown    0  2013.0  18.890000   
7670                      Deal or No Deal    1  2007.0  14.980000   
7671  Leisure Suit Larry: Box Office Bust    0  2009.0  22.200000   

      total sales/mil             genre  rating  user rating age platforms  \
0               10.57  Action Adventure     9.8          7.8   M       PS3   
1               11.09  Action Adventure     9.8          7.9   M      X360   
2               12.80            Action     9.7          9.1   E       Wii   
3                7.41            Action     9.7          9.1   E       Wii   
4                5.77  Action Adventure     9.7          8.0   M      XOne   
...               ...               ...     ...          ...  ..       ...   
7667             0.19            Sports     2.3          2.8   T      XOne   
7668             0.07           Driving     2.3          3.0   E        DS   
7669             0.05           Driving     2.2          1.3   T      X360   
7670             1.71     Miscellaneous     2.0          2.2   E        DS   
7671             0.10  Action Adventure     1.7          1.9   M       PS3   

     number of players             publisher  developer  
0                    1        Rockstar Games       1350  
1                    1        Rockstar Games       1350  
2                    1              Nintendo       1115  
3                    1              Nintendo       1116  
4                   32        Rockstar Games       1350  
...                ...                   ...        ...  
7667                 1               Ubisoft       1717  
7668         8  Online             Destineer       1799  
7669                 1            Activision         58  
7670                 2  Destination Software        116  
7671                 1                Funsta       1625  

[7672 rows x 13 columns]

In [4]:
lable = le.fit_transform(df2['genre'])
print(le.classes_)
print (lable)
df2 = df2.drop("genre", axis = 'columns')
df2 ['genre'] = lable
df2

['Action' 'Action Adventure' 'Action RPG' 'Adventure' 'Arcade' 'Breeding'
 'Card Battle' 'City Building' 'Compilation' 'Console-style RPG' 'Dancing'
 'Driving' 'Edutainment' 'Fantasy' 'Fighting' 'First-Person' 'Formula One'
 'GT ' 'General' 'Historic' 'Horror' 'Ice Hockey' 'Japanese-Style'
 'Massively Multiplayer Online' 'Military' 'Miscellaneous' 'Modern'
 'Music' 'Other' 'PC-style RPG' 'Party' 'Platformer' 'Puzzle' 'Racing'
 'Rally ' 'Real-Time' 'Role-Playing' 'Sci-Fi' 'Shooter' 'Sim' 'Simulation'
 'Sports' 'Strategy' 'Third-Person' 'Traditional' 'Tycoon' 'Virtual Life'
 'WWI' 'WWII']
[ 1  1  0 ... 11 25  1]


name  hit    Year      price  \
0                     Grand Theft Auto IV    1  2008.0  24.380000   
1                     Grand Theft Auto IV    1  2008.0  24.380000   
2                      Super Mario Galaxy    1  2007.0  69.990000   
3                    Super Mario Galaxy 2    1  2010.0  30.360000   
4                   Red Dead Redemption 2    1  2018.0  17.950000   
...                                   ...  ...     ...        ...   
7667                       Fighter Within    0  2013.0  11.680000   
7668                        Homie Rollerz    0  2008.0  31.958605   
7669             Fast & Furious: Showdown    0  2013.0  18.890000   
7670                      Deal or No Deal    1  2007.0  14.980000   
7671  Leisure Suit Larry: Box Office Bust    0  2009.0  22.200000   

      total sales/mil  rating  user rating age platforms number of players  \
0               10.57     9.8          7.8   M       PS3                 1   
1               11.09     9.8          7.9   M      X360                 1   
2               12.80     9.7          9.1   E       Wii                 1   
3                7.41     9.7          9.1   E       Wii                 1   
4                5.77     9.7          8.0   M      XOne                32   
...               ...     ...          ...  ..       ...               ...   
7667             0.19     2.3          2.8   T      XOne                 1   
7668             0.07     2.3          3.0   E        DS         8  Online   
7669             0.05     2.2          1.3   T      X360                 1   
7670             1.71     2.0          2.2   E        DS                 2   
7671             0.10     1.7          1.9   M       PS3                 1   

                 publisher  developer  genre  
0           Rockstar Games       1350      1  
1           Rockstar Games       1350      1  
2                 Nintendo       1115      0  
3                 Nintendo       1116      0  
4           Rockstar Games       1350      1  
...                    ...        ...    ...  
7667               Ubisoft       1717     41  
7668             Destineer       1799     11  
7669            Activision         58     11  
7670  Destination Software        116     25  
7671                Funsta       1625      1  

[7672 rows x 13 columns]

In [5]:
lable = le.fit_transform(df2['age'])
print(le.classes_)
print (lable)
df2 = df2.drop("age", axis = 'columns')
df2 ['age'] = lable
df2

['-' 'E' 'E10+' 'K-A' 'M' 'RP' 'T']
[4 4 1 ... 6 1 4]


name  hit    Year      price  \
0                     Grand Theft Auto IV    1  2008.0  24.380000   
1                     Grand Theft Auto IV    1  2008.0  24.380000   
2                      Super Mario Galaxy    1  2007.0  69.990000   
3                    Super Mario Galaxy 2    1  2010.0  30.360000   
4                   Red Dead Redemption 2    1  2018.0  17.950000   
...                                   ...  ...     ...        ...   
7667                       Fighter Within    0  2013.0  11.680000   
7668                        Homie Rollerz    0  2008.0  31.958605   
7669             Fast & Furious: Showdown    0  2013.0  18.890000   
7670                      Deal or No Deal    1  2007.0  14.980000   
7671  Leisure Suit Larry: Box Office Bust    0  2009.0  22.200000   

      total sales/mil  rating  user rating platforms number of players  \
0               10.57     9.8          7.8       PS3                 1   
1               11.09     9.8          7.9      X360                 1   
2               12.80     9.7          9.1       Wii                 1   
3                7.41     9.7          9.1       Wii                 1   
4                5.77     9.7          8.0      XOne                32   
...               ...     ...          ...       ...               ...   
7667             0.19     2.3          2.8      XOne                 1   
7668             0.07     2.3          3.0        DS         8  Online   
7669             0.05     2.2          1.3      X360                 1   
7670             1.71     2.0          2.2        DS                 2   
7671             0.10     1.7          1.9       PS3                 1   

                 publisher  developer  genre  age  
0           Rockstar Games       1350      1    4  
1           Rockstar Games       1350      1    4  
2                 Nintendo       1115      0    1  
3                 Nintendo       1116      0    1  
4           Rockstar Games       1350      1    4  
...                    ...        ...    ...  ...  
7667               Ubisoft       1717     41    6  
7668             Destineer       1799     11    1  
7669            Activision         58     11    6  
7670  Destination Software        116     25    1  
7671                Funsta       1625      1    4  

[7672 rows x 13 columns]

In [6]:
lable = le.fit_transform(df2['platforms'])
print(le.classes_)
print (lable)
df2 = df2.drop("platforms", axis = 'columns')
df2 ['platforms'] = lable
df2

['3DS' 'DS' 'NS' 'PC' 'PS2' 'PS3' 'PS4' 'PS5' 'PSP' 'PSV' 'Wii' 'WiiU'
 'X360' 'XOne']
[ 5 12 10 ... 12  1  5]


name  hit    Year      price  \
0                     Grand Theft Auto IV    1  2008.0  24.380000   
1                     Grand Theft Auto IV    1  2008.0  24.380000   
2                      Super Mario Galaxy    1  2007.0  69.990000   
3                    Super Mario Galaxy 2    1  2010.0  30.360000   
4                   Red Dead Redemption 2    1  2018.0  17.950000   
...                                   ...  ...     ...        ...   
7667                       Fighter Within    0  2013.0  11.680000   
7668                        Homie Rollerz    0  2008.0  31.958605   
7669             Fast & Furious: Showdown    0  2013.0  18.890000   
7670                      Deal or No Deal    1  2007.0  14.980000   
7671  Leisure Suit Larry: Box Office Bust    0  2009.0  22.200000   

      total sales/mil  rating  user rating number of players  \
0               10.57     9.8          7.8                 1   
1               11.09     9.8          7.9                 1   
2               12.80     9.7          9.1                 1   
3                7.41     9.7          9.1                 1   
4                5.77     9.7          8.0                32   
...               ...     ...          ...               ...   
7667             0.19     2.3          2.8                 1   
7668             0.07     2.3          3.0         8  Online   
7669             0.05     2.2          1.3                 1   
7670             1.71     2.0          2.2                 2   
7671             0.10     1.7          1.9                 1   

                 publisher  developer  genre  age  platforms  
0           Rockstar Games       1350      1    4          5  
1           Rockstar Games       1350      1    4         12  
2                 Nintendo       1115      0    1         10  
3                 Nintendo       1116      0    1         10  
4           Rockstar Games       1350      1    4         13  
...                    ...        ...    ...  ...        ...  
7667               Ubisoft       1717     41    6         13  
7668             Destineer       1799     11    1          1  
7669            Activision         58     11    6         12  
7670  Destination Software        116     25    1          1  
7671                Funsta       1625      1    4          5  

[7672 rows x 13 columns]

In [7]:
lable = le.fit_transform(df2['number of players'])
print(le.classes_)
print (lable)
df2 = df2.drop("number of players", axis = 'columns')
df2 ['number of players'] = lable
df2

['1' '1-10' '1-12' '1-3' '1-5' '1-6' '1-64' '10' '10  Online' '100' '12'
 '12  Online' '14  Online' '16' '16  Online' '18' '2' '2  Online'
 '24  Online' '3  Online' '30' '32' '32  Online' '4' '4  Online' '40'
 '44  Online' '5' '5  Online' '6' '6  Online' '64  Online' '64+'
 '64+  Online' '8' '8  Online' 'Up to 14' 'Up to 20' 'Up to 22' 'Up to 24'
 'Up to 3' 'Up to 60' 'Up to 64' 'Up to 9' 'Up to more than 64']
[ 0  0  0 ...  0 16  0]


name  hit    Year      price  \
0                     Grand Theft Auto IV    1  2008.0  24.380000   
1                     Grand Theft Auto IV    1  2008.0  24.380000   
2                      Super Mario Galaxy    1  2007.0  69.990000   
3                    Super Mario Galaxy 2    1  2010.0  30.360000   
4                   Red Dead Redemption 2    1  2018.0  17.950000   
...                                   ...  ...     ...        ...   
7667                       Fighter Within    0  2013.0  11.680000   
7668                        Homie Rollerz    0  2008.0  31.958605   
7669             Fast & Furious: Showdown    0  2013.0  18.890000   
7670                      Deal or No Deal    1  2007.0  14.980000   
7671  Leisure Suit Larry: Box Office Bust    0  2009.0  22.200000   

      total sales/mil  rating  user rating             publisher  developer  \
0               10.57     9.8          7.8        Rockstar Games       1350   
1               11.09     9.8          7.9        Rockstar Games       1350   
2               12.80     9.7          9.1              Nintendo       1115   
3                7.41     9.7          9.1              Nintendo       1116   
4                5.77     9.7          8.0        Rockstar Games       1350   
...               ...     ...          ...                   ...        ...   
7667             0.19     2.3          2.8               Ubisoft       1717   
7668             0.07     2.3          3.0             Destineer       1799   
7669             0.05     2.2          1.3            Activision         58   
7670             1.71     2.0          2.2  Destination Software        116   
7671             0.10     1.7          1.9                Funsta       1625   

      genre  age  platforms  number of players  
0         1    4          5                  0  
1         1    4         12                  0  
2         0    1         10                  0  
3         0    1         10                  0  
4         1    4         13                 21  
...     ...  ...        ...                ...  
7667     41    6         13                  0  
7668     11    1          1                 35  
7669     11    6         12                  0  
7670     25    1          1                 16  
7671      1    4          5                  0  

[7672 rows x 13 columns]

In [8]:
lable = le.fit_transform(df2['publisher'])
print(le.classes_)
print (lable)
df2 = df2.drop("publisher", axis = 'columns')
df2 ['publisher'] = lable
df2.set_index('name',inplace=True)
display(df2)

['10tacle Studios' '11 bit studios' '1C' '2K Games' '2K Play' '2K Sports'
 '3909' '3DO' '505 Games' '5pb' '704Games' 'Abbey Games' 'Acclaim'
 'Acid Wizard Studio' 'Activision' 'Activision Blizzard' 'Adult Swim'
 'Agetec' 'Agetec Inc.' 'Aksys Games' 'Alientrap' 'All in! Games'
 'Almost Human' 'Amanita Design' 'Amazon Game Studios' 'Amplitude Studios'
 'Analgesic Productions' 'Angry Mob Games' 'Annapurna Interactive'
 'Aqua Plus' 'Arc System Works' 'Arcen Games, LLC' 'Arush Entertainment'
 'Ascaron Entertainment GmbH' 'Aspyr' 'Asteroid Base'
 'Asymmetric Publications' 'Atari' 'Atari SA' 'Aterdux Entertainment'
 'Atlus' 'Atlus Co.' 'Autumn Games' 'Avalanche Studios' 'Badland Games'
 'Bam Entertainment' 'Bandai' 'Bandai America Inc.' 'Bandai Namco Games'
 'Battlefront.com' 'Beatnik Games' 'Behold Studios' 'BetaDwarf'
 'Bethesda Softworks' 'Big Sandwich Games, Inc.' 'Bigben Interactive'
 'Bishop Games' 'Bit Blot' 'Bitbox Ltd.' 'Black Bean Games'
 'Black Forest Games' 'Black Label Games' 'Bl

hit    Year      price  total sales/mil  \
name                                                                           
Grand Theft Auto IV                    1  2008.0  24.380000            10.57   
Grand Theft Auto IV                    1  2008.0  24.380000            11.09   
Super Mario Galaxy                     1  2007.0  69.990000            12.80   
Super Mario Galaxy 2                   1  2010.0  30.360000             7.41   
Red Dead Redemption 2                  1  2018.0  17.950000             5.77   
...                                  ...     ...        ...              ...   
Fighter Within                         0  2013.0  11.680000             0.19   
Homie Rollerz                          0  2008.0  31.958605             0.07   
Fast & Furious: Showdown               0  2013.0  18.890000             0.05   
Deal or No Deal                        1  2007.0  14.980000             1.71   
Leisure Suit Larry: Box Office Bust    0  2009.0  22.200000             0.10   

                                     rating  user rating  developer  genre  \
name                                                                         
Grand Theft Auto IV                     9.8          7.8       1350      1   
Grand Theft Auto IV                     9.8          7.9       1350      1   
Super Mario Galaxy                      9.7          9.1       1115      0   
Super Mario Galaxy 2                    9.7          9.1       1116      0   
Red Dead Redemption 2                   9.7          8.0       1350      1   
...                                     ...          ...        ...    ...   
Fighter Within                          2.3          2.8       1717     41   
Homie Rollerz                           2.3          3.0       1799     11   
Fast & Furious: Showdown                2.2          1.3         58     11   
Deal or No Deal                         2.0          2.2        116     25   
Leisure Suit Larry: Box Office Bust     1.7          1.9       1625      1   

                                     age  platforms  number of players  \
name                                                                     
Grand Theft Auto IV                    4          5                  0   
Grand Theft Auto IV                    4         12                  0   
Super Mario Galaxy                     1         10                  0   
Super Mario Galaxy 2                   1         10                  0   
Red Dead Redemption 2                  4         13                 21   
...                                  ...        ...                ...   
Fighter Within                         6         13                  0   
Homie Rollerz                          1          1                 35   
Fast & Furious: Showdown               6         12                  0   
Deal or No Deal                        1          1                 16   
Leisure Suit Larry: Box Office Bust    4          5                  0   

                                     publisher  
name                                            
Grand Theft Auto IV                        418  
Grand Theft Auto IV                        418  
Super Mario Galaxy                         353  
Super Mario Galaxy 2                       353  
Red Dead Redemption 2                      418  
...                                        ...  
Fighter Within                             539  
Homie Rollerz                              126  
Fast & Furious: Showdown                    14  
Deal or No Deal                            125  
Leisure Suit Larry: Box Office Bust        180  

[7672 rows x 12 columns]

In [9]:
# saving the DataFrame
df2.to_csv("numeric_DF#2.csv")